server:
  port: 9090
spring:
  application:
    name: gateway-server
  config:
    import: configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: config-server
          uri: lb://config-server
          predicates:
            - Path=/**