server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: academic-service
          uri: lb://ACADEMIC-SERVICE
          predicates:
            - Path=/api/courses/**,/api/periods/**,/api/academics/**
        - id: attendance-service
          uri: lb://ATTENDANCE-SERVICE
          predicates:
            - Path=/api/attendance/**
